import sys

def gro_to_pdb(gro_file, pdb_file):
    with open(gro_file, 'r') as f:
        lines = f.readlines()
    
    # GRO line format: 
    # resid(5) resname(5) atomname(5) atomid(5) x(8.3) y(8.3) z(8.3)
    # PDB format:
    # ATOM  (6) serial(5) name(4) resName(3) chain(1) resSeq(4) ... x(8.3) y(8.3) z(8.3)
    
    with open(pdb_file, 'w') as f:
        f.write("REMARK    GENERATED BY CONVERTER\n")
        
        # Skip title (0) and num_atoms (1)
        # Verify lines
        if len(lines) < 3:
            print("Error: Invalid GRO file")
            return
            
        atom_count = int(lines[1])
        
        for i in range(2, 2 + atom_count):
            line = lines[i]
            resid_str = line[0:5].strip()
            resname = line[5:10].strip()
            atomname = line[10:15].strip()
            atomid = int(line[15:20])
            x = float(line[20:28]) * 10.0 # nm to Angstrom
            y = float(line[28:36]) * 10.0
            z = float(line[36:44]) * 10.0
            
            # Formating PDB line
            # ATOM   1    C      UNK     1      14.000  12.000   5.000  1.00  0.00
            f.write(f"ATOM  {atomid:5d} {atomname:<4s} {resname[:3]:<3s} A{int(resid_str):4d}    {x:8.3f}{y:8.3f}{z:8.3f}  1.00  0.00           {atomname[0]}\n")
            
        f.write("END\n")
    print(f"Distances converted from nm (GRO) to Angstroms (PDB). Saved to {pdb_file}")

if __name__ == "__main__":
    gro_to_pdb("phenol.gro", "phenol_SwissParam.pdb")
